"""Initial schema: extensions, enum types, users, profiles, refresh tokens

Revision ID: 0001_initial
Revises:
Created: 2026-09-02

Written by hand rather than autogenerated. Autogenerate handles native enum
types poorly — it emits CREATE TYPE inline inside CREATE TABLE, so a second
table referencing the same type fails with "type already exists", and the
downgrade leaves orphaned types behind. Creating the types explicitly up front
and referencing them with create_type=False avoids both problems.

Extensions are created here as well as in the compose init script. The init
script only runs for a fresh local volume; a managed database such as Cloud SQL
never runs it (database.md section 5). CREATE EXTENSION IF NOT EXISTS is
idempotent, so both paths are safe.

Note on constraint names: check constraints are given BARE names here
(`years_non_negative`, not `ck_profiles_years_non_negative`). Alembic applies the
metadata naming convention `ck_%(table_name)s_%(constraint_name)s` to whatever
name is supplied, so a pre-prefixed name produces
`ck_profiles_ck_profiles_years_non_negative` in the database and permanent drift
against the models. Primary key, unique and foreign key conventions contain no
`%(constraint_name)s` token, so their explicit names pass through unchanged.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Enum types created before any table references them.
ENUM_TYPES: dict[str, tuple[str, ...]] = {
    "user_role": ("USER", "ADMIN"),
    "auth_provider": ("LOCAL", "GOOGLE"),
    "experience_level": (
        "INTERN",
        "ENTRY",
        "JUNIOR",
        "MID",
        "SENIOR",
        "LEAD",
        "PRINCIPAL",
    ),
    "education_level": (
        "NONE",
        "HIGH_SCHOOL",
        "DIPLOMA",
        "BACHELORS",
        "MASTERS",
        "DOCTORATE",
    ),
    "work_mode": ("ONSITE", "HYBRID", "REMOTE"),
    "employment_type": (
        "FULL_TIME",
        "PART_TIME",
        "CONTRACT",
        "INTERNSHIP",
        "TEMPORARY",
    ),
}


def _enum(name: str) -> postgresql.ENUM:
    """Reference an already-created type without attempting to create it."""
    return postgresql.ENUM(name=name, create_type=False)


def upgrade() -> None:
    # ------------------------------------------------------------ extensions
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # pgvector is not used until Phase 6, but enabling it now means the
    # extension requirement is discovered on a fresh database today rather than
    # on the day the embedding work lands (ADR-002).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ------------------------------------------------------------ enum types
    for type_name, values in ENUM_TYPES.items():
        rendered = ", ".join(f"'{v}'" for v in values)
        op.execute(f"CREATE TYPE {type_name} AS ENUM ({rendered})")

    # ------------------------------------------------------------ users
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column(
            "auth_provider",
            _enum("auth_provider"),
            server_default="LOCAL",
            nullable=False,
        ),
        sa.Column("oauth_subject", sa.Text(), nullable=True),
        sa.Column("role", _enum("user_role"), server_default="USER", nullable=False),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("email", name="uq_users_email"),
        # An account must always carry a usable credential: a local password or
        # an OAuth subject. Enforced here so no code path can create an account
        # that cannot authenticate at all (database.md section 3.1).
        sa.CheckConstraint(
            "(auth_provider = 'LOCAL' AND password_hash IS NOT NULL) "
            "OR (auth_provider <> 'LOCAL' AND oauth_subject IS NOT NULL)",
            name="auth_credential_present",
        ),
    )
    # Partial unique index: without the WHERE clause, every local account has
    # oauth_subject NULL and a plain unique index would still allow duplicates
    # (NULLs never compare equal), but the index would be needlessly large.
    op.create_index(
        "ux_users_oauth",
        "users",
        ["auth_provider", "oauth_subject"],
        unique=True,
        postgresql_where=sa.text("oauth_subject IS NOT NULL"),
    )

    # ------------------------------------------------------------ profiles
    op.create_table(
        "profiles",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("headline", sa.String(length=300), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("linkedin_url", sa.Text(), nullable=True),
        sa.Column("github_url", sa.Text(), nullable=True),
        sa.Column("portfolio_url", sa.Text(), nullable=True),
        sa.Column("years_of_experience", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("current_experience_level", _enum("experience_level"), nullable=True),
        sa.Column("highest_education", _enum("education_level"), nullable=True),
        sa.Column(
            "target_roles",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "preferred_locations",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column(
            "preferred_work_modes",
            postgresql.ARRAY(_enum("work_mode")),
            server_default=sa.text("'{}'::work_mode[]"),
            nullable=False,
        ),
        sa.Column(
            "preferred_employment_types",
            postgresql.ARRAY(_enum("employment_type")),
            server_default=sa.text("'{}'::employment_type[]"),
            nullable=False,
        ),
        sa.Column(
            "min_salary_expectation", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column("salary_currency", sa.String(length=3), nullable=True),
        sa.Column(
            "open_to_relocation",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column("preferences_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_profiles"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_profiles_user_id_users",
            ondelete="CASCADE",
        ),
        # UNIQUE is what makes this one-to-one. Relying on the ORM relationship
        # alone would let a background worker create a second profile.
        sa.UniqueConstraint("user_id", name="uq_profiles_user_id"),
        sa.CheckConstraint(
            "years_of_experience IS NULL OR years_of_experience >= 0",
            name="years_non_negative",
        ),
        sa.CheckConstraint(
            "min_salary_expectation IS NULL OR min_salary_expectation >= 0",
            name="salary_non_negative",
        ),
        sa.CheckConstraint(
            "salary_currency IS NULL OR char_length(salary_currency) = 3",
            name="currency_is_iso4217",
        ),
        sa.CheckConstraint(
            "country_code IS NULL OR char_length(country_code) = 2",
            name="country_is_iso3166",
        ),
    )

    # ------------------------------------------------------------ refresh_tokens
    op.create_table(
        "refresh_tokens",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        # SHA-256 hex is exactly 64 characters. Only the hash is stored, so a
        # database compromise yields no usable refresh tokens.
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="pk_refresh_tokens"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name="fk_refresh_tokens_user_id_users",
            ondelete="CASCADE",
        ),
        # SET NULL rather than CASCADE: pruning an old token must not delete the
        # newer token that replaced it, which is still an active session.
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["refresh_tokens.id"],
            name="fk_refresh_tokens_replaced_by_id_refresh_tokens",
            ondelete="SET NULL",
        ),
        sa.UniqueConstraint("token_hash", name="uq_refresh_tokens_token_hash"),
    )
    op.create_index("ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"])
    # Reuse detection revokes an entire rotation family at once, which is a
    # lookup by family_id (US-1.3 AC2).
    op.create_index("ix_refresh_tokens_family_id", "refresh_tokens", ["family_id"])


def downgrade() -> None:
    op.drop_index("ix_refresh_tokens_family_id", table_name="refresh_tokens")
    op.drop_index("ix_refresh_tokens_user_id", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")

    op.drop_table("profiles")

    op.drop_index("ux_users_oauth", table_name="users")
    op.drop_table("users")

    # Types must be dropped after the tables that reference them.
    for type_name in reversed(list(ENUM_TYPES)):
        op.execute(f"DROP TYPE IF EXISTS {type_name}")

    # Extensions are deliberately left in place. Dropping them would break any
    # other schema in the same database, and they are harmless when unused.
