"""Add work history, education, projects and certifications

Revision ID: 0005_career_entities
Revises: 0004_jobs_and_companies
Created: 2026-09-03

Autogenerated, then adjusted: alembic renders enum columns as inline sa.Enum,
which emits CREATE TYPE and fails because education_level, employment_type and
work_mode already exist (see 0001). They are referenced with create_type=False
instead.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0005_career_entities"
down_revision: str | None = "0004_jobs_and_companies"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _enum(name: str) -> postgresql.ENUM:
    """Reference an already-created type without attempting to create it."""
    return postgresql.ENUM(name=name, create_type=False)


def upgrade() -> None:
    op.create_table(
        "certifications",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("issuer", sa.String(length=200), nullable=True),
        sa.Column("credential_id", sa.String(length=200), nullable=True),
        sa.Column("credential_url", sa.Text(), nullable=True),
        sa.Column("issued_date", sa.Date(), nullable=True),
        sa.Column("expires_date", sa.Date(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("extraction_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column(
            "is_user_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("source_version_id", sa.UUID(), nullable=True),
        sa.Column("content_key", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "extraction_confidence IS NULL OR (extraction_confidence >= 0 AND extraction_confidence <= 1)",
            name=op.f("ck_certifications_confidence_is_fraction"),
        ),
        sa.CheckConstraint(
            "issued_date IS NULL OR expires_date IS NULL OR expires_date >= issued_date",
            name=op.f("ck_certifications_dates_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["resume_versions.id"],
            name=op.f("fk_certifications_source_version_id_resume_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_certifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certifications")),
    )
    op.create_index(
        "ix_certifications_source", "certifications", ["source_version_id"], unique=False
    )
    op.create_index("ix_certifications_user", "certifications", ["user_id"], unique=False)
    op.create_index(
        "ux_certifications_content", "certifications", ["user_id", "content_key"], unique=True
    )
    op.create_table(
        "education_records",
        sa.Column("institution", sa.String(length=200), nullable=False),
        sa.Column("degree", sa.String(length=200), nullable=True),
        sa.Column("field_of_study", sa.String(length=200), nullable=True),
        sa.Column("education_level", _enum("education_level"), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("grade", sa.String(length=50), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("extraction_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column(
            "is_user_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("source_version_id", sa.UUID(), nullable=True),
        sa.Column("content_key", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT (is_current AND end_date IS NOT NULL)",
            name=op.f("ck_education_records_current_has_no_end"),
        ),
        sa.CheckConstraint(
            "extraction_confidence IS NULL OR (extraction_confidence >= 0 AND extraction_confidence <= 1)",
            name=op.f("ck_education_records_confidence_is_fraction"),
        ),
        sa.CheckConstraint(
            "start_date IS NULL OR end_date IS NULL OR end_date >= start_date",
            name=op.f("ck_education_records_dates_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["resume_versions.id"],
            name=op.f("fk_education_records_source_version_id_resume_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_education_records_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_education_records")),
    )
    op.create_index(
        "ix_education_records_source", "education_records", ["source_version_id"], unique=False
    )
    op.create_index("ix_education_records_user", "education_records", ["user_id"], unique=False)
    op.create_index(
        "ux_education_records_content", "education_records", ["user_id", "content_key"], unique=True
    )
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("repository_url", sa.Text(), nullable=True),
        sa.Column(
            "highlights",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("extraction_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column(
            "is_user_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("source_version_id", sa.UUID(), nullable=True),
        sa.Column("content_key", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT (is_current AND end_date IS NOT NULL)", name=op.f("ck_projects_current_has_no_end")
        ),
        sa.CheckConstraint(
            "extraction_confidence IS NULL OR (extraction_confidence >= 0 AND extraction_confidence <= 1)",
            name=op.f("ck_projects_confidence_is_fraction"),
        ),
        sa.CheckConstraint(
            "start_date IS NULL OR end_date IS NULL OR end_date >= start_date",
            name=op.f("ck_projects_dates_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["resume_versions.id"],
            name=op.f("fk_projects_source_version_id_resume_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_projects_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index("ix_projects_source", "projects", ["source_version_id"], unique=False)
    op.create_index("ix_projects_user", "projects", ["user_id"], unique=False)
    op.create_index("ux_projects_content", "projects", ["user_id", "content_key"], unique=True)
    op.create_table(
        "work_experiences",
        # Nullable: "Freelance Web Developer" is a real entry with no employer.
        sa.Column("company_name", sa.String(length=200), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("employment_type", _enum("employment_type"), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("work_mode", _enum("work_mode"), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "highlights",
            postgresql.ARRAY(sa.Text()),
            server_default=sa.text("'{}'::text[]"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("extraction_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column(
            "is_user_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("source_version_id", sa.UUID(), nullable=True),
        sa.Column("content_key", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT (is_current AND end_date IS NOT NULL)",
            name=op.f("ck_work_experiences_current_has_no_end"),
        ),
        sa.CheckConstraint(
            "extraction_confidence IS NULL OR (extraction_confidence >= 0 AND extraction_confidence <= 1)",
            name=op.f("ck_work_experiences_confidence_is_fraction"),
        ),
        sa.CheckConstraint(
            "start_date IS NULL OR end_date IS NULL OR end_date >= start_date",
            name=op.f("ck_work_experiences_dates_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["resume_versions.id"],
            name=op.f("fk_work_experiences_source_version_id_resume_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_work_experiences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_experiences")),
    )
    op.create_index(
        "ix_work_experiences_source", "work_experiences", ["source_version_id"], unique=False
    )
    op.create_index("ix_work_experiences_user", "work_experiences", ["user_id"], unique=False)
    op.create_index(
        "ux_work_experiences_content", "work_experiences", ["user_id", "content_key"], unique=True
    )


def downgrade() -> None:
    op.drop_index("ux_work_experiences_content", table_name="work_experiences")
    op.drop_index("ix_work_experiences_user", table_name="work_experiences")
    op.drop_index("ix_work_experiences_source", table_name="work_experiences")
    op.drop_table("work_experiences")
    op.drop_index("ux_projects_content", table_name="projects")
    op.drop_index("ix_projects_user", table_name="projects")
    op.drop_index("ix_projects_source", table_name="projects")
    op.drop_table("projects")
    op.drop_index("ux_education_records_content", table_name="education_records")
    op.drop_index("ix_education_records_user", table_name="education_records")
    op.drop_index("ix_education_records_source", table_name="education_records")
    op.drop_table("education_records")
    op.drop_index("ux_certifications_content", table_name="certifications")
    op.drop_index("ix_certifications_user", table_name="certifications")
    op.drop_index("ix_certifications_source", table_name="certifications")
    op.drop_table("certifications")
