"""Add applications — saved jobs and the applied flag

Revision ID: 0007_applications
Revises: 0006_job_source_partner_api
Created: 2026-09-05

The first slice of database.md section 3.7 (US-7.0). Two statuses rather than
seven, and without resume_version_id, match_score_at_apply, next_action_at,
source, notes or outcome_reason — each of those has a precondition that does not
exist yet, and a permanently-null column reads to analytics as a value rather
than as an absence.

Written by hand rather than autogenerated: alembic renders an enum column as an
inline sa.Enum, which re-emits CREATE TYPE and fails the second time the type is
referenced (see 0005). The type is created once here and referenced with
create_type=False.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0007_applications"
down_revision: str | None = "0006_job_source_partner_api"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # A fresh CREATE TYPE is safe inside the transaction env.py wraps every
    # migration in. Only ALTER TYPE ... ADD VALUE carries the restriction that
    # the new value cannot be used in the same transaction (see 0006).
    op.execute("CREATE TYPE application_status AS ENUM ('SAVED', 'APPLIED')")

    op.create_table(
        "applications",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("job_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(name="application_status", create_type=False),
            server_default=sa.text("'SAVED'::application_status"),
            nullable=False,
        ),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
        # CASCADE: what a user saved is their data and goes with the account.
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_applications_user_id_users"),
            ondelete="CASCADE",
        ),
        # RESTRICT: an application is historical fact. Cascading it away with a
        # job would lose funnel data silently (database.md section 3.7).
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_applications_job_id_jobs"),
            ondelete="RESTRICT",
        ),
        # Holds in both directions, so unmarking applied must clear the date.
        sa.CheckConstraint(
            "(status = 'APPLIED') = (applied_at IS NOT NULL)",
            name=op.f("ck_applications_applied_has_timestamp"),
        ),
    )

    # Partial, and that is the whole idempotency mechanism for the save toggle:
    # at most one live application per (user, job). It also deliberately does not
    # cover tombstones, so unsave-then-re-save inserts a fresh SAVED row rather
    # than resurrecting an old APPLIED one.
    op.create_index(
        "ux_applications_user_job",
        "applications",
        ["user_id", "job_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # RESTRICT makes every DELETE on jobs check this table; without an index
    # that is a sequential scan per row deleted.
    op.create_index("ix_applications_job_id", "applications", ["job_id"])
    op.create_index(
        op.f("ix_applications_deleted_at"), "applications", ["deleted_at"], unique=False
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_applications_deleted_at"), table_name="applications")
    op.drop_index("ix_applications_job_id", table_name="applications")
    op.drop_index("ux_applications_user_job", table_name="applications")
    op.drop_table("applications")
    op.execute("DROP TYPE application_status")
